version: '3.8'
services:
  web:
    image: cs353app
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py  
    volumes:
      - ./api:/api
    depends_on:
      - db  
    working_dir: /api
    command: ["python", "api.py"]
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password1212
      MYSQL_DATABASE: cs353dbproject
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
