version: '3'
services:
  web:
    image: ticketify
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    working_dir: /api
    command: python api.py
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password1212
      MYSQL_DATABASE: cs353dbproject
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
